export const PARTY_GAME_CONFIGS = {
  neontagarena: {
    id: 'neontagarena',
    title: 'Neon Tag Arena',
    subtitle: 'Fast 3D tag for 3-4 players on one keyboard.',
    objective: 'Hold the crown the longest before time runs out.',
    variant: 'tag',
    roundSeconds: 90,
    arenaSize: 34,
    baseSpeed: 8.2,
    palette: {
      background: 0x071326,
      floor: 0x112d4f,
      wall: 0x1dd3f8,
      accent: 0xffdf6e,
      fog: 0x09162a,
    },
  },
  crystalcometclash: {
    id: 'crystalcometclash',
    title: 'Crystal Comet Clash',
    subtitle: 'Collect unstable crystals while dodging shock mines.',
    objective: 'Farm the most crystal score in a single round.',
    variant: 'collect',
    roundSeconds: 85,
    arenaSize: 32,
    baseSpeed: 8.6,
    collectPoints: 4,
    hazardEnabled: true,
    palette: {
      background: 0x101228,
      floor: 0x273469,
      wall: 0xff6b9a,
      accent: 0x78ffd6,
      fog: 0x14192f,
    },
  },
  bombrelay3d: {
    id: 'bombrelay3d',
    title: 'Bomb Relay 3D',
    subtitle: 'Pass the bomb before the fuse detonates.',
    objective: 'Stay away from the bomb when the timer pops.',
    variant: 'bomb',
    roundSeconds: 95,
    arenaSize: 34,
    baseSpeed: 8.4,
    bombPenalty: 16,
    palette: {
      background: 0x1e1109,
      floor: 0x44240f,
      wall: 0xffa000,
      accent: 0xff3d00,
      fog: 0x22150f,
    },
  },
  zonecontrol3d: {
    id: 'zonecontrol3d',
    title: 'Zone Control 3D',
    subtitle: 'Fight for the moving capture ring.',
    objective: 'Stand in the zone to earn control points.',
    variant: 'zone',
    roundSeconds: 90,
    arenaSize: 35,
    baseSpeed: 8,
    zoneRate: 4.3,
    zoneRadius: 5.6,
    palette: {
      background: 0x031b1f,
      floor: 0x0d3b42,
      wall: 0x20e3b2,
      accent: 0xf9f871,
      fog: 0x07262b,
    },
  },
  meteormayhem3d: {
    id: 'meteormayhem3d',
    title: 'Meteor Mayhem 3D',
    subtitle: 'A meteor storm survival contest.',
    objective: 'Stay alive and keep moving for survival points.',
    variant: 'meteor',
    roundSeconds: 80,
    arenaSize: 33,
    baseSpeed: 8.8,
    survivalRate: 2.6,
    meteorEvery: 0.8,
    palette: {
      background: 0x190d2a,
      floor: 0x2f1f45,
      wall: 0xaf7bff,
      accent: 0x4ef0ff,
      fog: 0x1f1335,
    },
  },
  quaddashcircuit: {
    id: 'quaddashcircuit',
    title: 'Quad Dash Circuit',
    subtitle: 'Sprint to checkpoints in a 3D arena race.',
    objective: 'Touch as many checkpoints as possible.',
    variant: 'dash',
    roundSeconds: 85,
    arenaSize: 36,
    baseSpeed: 9,
    checkpointPoints: 6,
    palette: {
      background: 0x061f14,
      floor: 0x0f4d37,
      wall: 0x41f296,
      accent: 0xffd166,
      fog: 0x0a2b1d,
    },
  },
  laserlootarena: {
    id: 'laserlootarena',
    title: 'Laser Loot Arena',
    subtitle: 'Loot core cells in a glowing laser dome.',
    objective: 'Grab loot and avoid hot zones for max score.',
    variant: 'collect',
    roundSeconds: 88,
    arenaSize: 34,
    baseSpeed: 8.7,
    collectPoints: 5,
    hazardEnabled: true,
    palette: {
      background: 0x081622,
      floor: 0x12344d,
      wall: 0x5fd9ff,
      accent: 0xff4f8b,
      fog: 0x0d1f2e,
    },
  },
  crownrush3d: {
    id: 'crownrush3d',
    title: 'Crown Rush 3D',
    subtitle: 'Ultra-fast king-of-tag showdown.',
    objective: 'Rush the crown carrier and steal the lead.',
    variant: 'tag',
    roundSeconds: 75,
    arenaSize: 31,
    baseSpeed: 9.2,
    tagRate: 4.9,
    palette: {
      background: 0x2a0d12,
      floor: 0x4a1f28,
      wall: 0xff6b6b,
      accent: 0xffec99,
      fog: 0x301219,
    },
  },
  orbharvest3d: {
    id: 'orbharvest3d',
    title: 'Orb Harvest 3D',
    subtitle: 'Classic orb collection with speed bursts.',
    objective: 'Collect orbs faster than everyone else.',
    variant: 'collect',
    roundSeconds: 92,
    arenaSize: 35,
    baseSpeed: 8.1,
    collectPoints: 4,
    palette: {
      background: 0x0d1d0b,
      floor: 0x224b1f,
      wall: 0x79e46d,
      accent: 0x9bf6ff,
      fog: 0x132913,
    },
  },
  hoverbump3d: {
    id: 'hoverbump3d',
    title: 'Hover Bump 3D',
    subtitle: 'Body-check rivals out of the scoring ring.',
    objective: 'Hold the tiny zone while bumping others out.',
    variant: 'zone',
    roundSeconds: 82,
    arenaSize: 30,
    baseSpeed: 9.4,
    zoneRate: 5.3,
    zoneRadius: 4.2,
    palette: {
      background: 0x111111,
      floor: 0x2b2b2b,
      wall: 0xf07167,
      accent: 0x00afb9,
      fog: 0x1a1a1a,
    },
  },
  pulsepit3d: {
    id: 'pulsepit3d',
    title: 'Pulse Pit 3D',
    subtitle: 'Hot-potato chaos in a compact pit.',
    objective: 'Dodge pulse bomb penalties and survive the round.',
    variant: 'bomb',
    roundSeconds: 78,
    arenaSize: 29,
    baseSpeed: 9.1,
    bombPenalty: 18,
    palette: {
      background: 0x120522,
      floor: 0x2b1145,
      wall: 0xcd5cff,
      accent: 0x00f5d4,
      fog: 0x17082b,
    },
  },
  turbototem3d: {
    id: 'turbototem3d',
    title: 'Turbo Totem 3D',
    subtitle: 'Dash race around a shifting totem beacon.',
    objective: 'Claim totem checkpoints before opponents.',
    variant: 'dash',
    roundSeconds: 86,
    arenaSize: 35,
    baseSpeed: 9,
    checkpointPoints: 7,
    palette: {
      background: 0x1a1304,
      floor: 0x3d2c08,
      wall: 0xffb703,
      accent: 0x8ecae6,
      fog: 0x241b08,
    },
  },
  vaultraid3d: {
    id: 'vaultraid3d',
    title: 'Vault Raid 3D',
    subtitle: 'Steal energy vaults in a dense arena.',
    objective: 'Raid high-value vault orbs for the top score.',
    variant: 'collect',
    roundSeconds: 84,
    arenaSize: 33,
    baseSpeed: 8.9,
    collectPoints: 6,
    hazardEnabled: true,
    palette: {
      background: 0x071a17,
      floor: 0x113d37,
      wall: 0x33d9b2,
      accent: 0xff9f1c,
      fog: 0x0b2824,
    },
  },
};
